### ISSUE TITLE
README.md may contain some outdated example code

### ISSUE THREAD

**Issue by oscar-raunio** [null93/drawille#2]
With the canvas example, it creates a for loop with a getWidth() * 10, which is out of bounds of the manipulated canvas. Some better values would be Canvas(75,6) with the for loop multiplying the width by 8.

Heres my output with the new values values.
[output.txt](https://github.com/null93/drawille/files/2255486/output.txt)

Heres what I get usually.
[output2.txt](https://github.com/null93/drawille/files/2255500/output2.txt)

(great work btw!)

**Comment by null93** [comment]
Thanks! Must have overlooked that, nice catch!
