### ISSUE TITLE
Create an animation with the library

### ISSUE THREAD

**Issue by jabrena** [null93/drawille#5]
Hi, 

I would like to know if it is possible to use the library to create an animation refreshing the terminal with the animation.

Many thanks in advance.

Juan Antonio

**Comment by null93** [comment]
Hey!

You definitely could create an animation if you wanted. You just have to do the following inside a loop: draw a frame, sleep, and then clear the screen.

**Comment by jabrena** [comment]
Could you provide a simple example please?

**Comment by null93** [comment]
I will leave that as an exercise for you.

**Comment by jabrena** [comment]
Many thanks Rafael,

tell me when I could test that example :)

Juan Antonio
