### ISSUE TITLE
drawing animation on a refreshable braille display

### ISSUE THREAD

**Issue by denizsincar29** [null93/drawille#6]
hello.
is this program made for sending unicode braille to a braille display to feal tactile animations for blind? am i right?
i got this repository and tested it. it doesn't send braille animations to my refreshible braille display so i cannot feal it with my fingers. i am blind. a refreshable braille display is an electromechanical device that raises dots on a surface to display text in braille. please tell me how to get this thing send the animations to a braille display. thank you

**Comment by null93** [comment]
Hello! Unfortunately this is not what this program does. It is a java port of a program known as drawille. Drawille simply makes drawing in a text terminal easier. It uses braille characters in order to draw.

I hope you find what you are looking for and I wish you the best!

**Comment by denizsincar29** [comment]
so sorry. i thaught that if braille, than it is definitely something for blind. we use screen reading program for blind to control our computers. and i was looking some github repos for braille display.
